# version: "3.8"
# services:
#   app:
#     image: backend
#     environment:
#       REDIS_HOST: redis
#       REDIS_PORT: 6100
#     depends_on:
#       - redis
#
#     ports:
#       - "7000:7000"
#     networks:
#       - app-network
#
#   redis:
#     image: redis:latest
#     ports:
#       - "6100:6100"
#     networks:
#       - app-network
#
# networks:
#   app-network:
#     driver: bridge

version: "3.8"
services:
  app:
    image: backend
    environment:
      REDIS_HOST: redis
      REDIS_PORT: redis
